spring:
  application:
    name: livros API
  datasource:
    url: jdbc:h2:mem:livros
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console